FROM openjdk:17.0.12-jdk-slim
# Spécifier le répertoire de travail
RUN mkdir -p /workspace

WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
RUN mvn -f pom.xml clean package

FROM openjdk:17.0.12-jdk-alpine
# Copier le fichier JAR du backend dans le container
COPY --from=build /workspace/target/*.jar app.jar
# Exposer le port utilisé par Spring Boot
EXPOSE 8080
# Exécuter l'application Spring Boot
ENTRYPOINT ["java", "-jar", "app.jar"]