FROM openjdk:25-jdk-slim
# Spécifier le répertoire de travail
WORKDIR /springboot-deploy
# Copier le fichier JAR du backend dans le container
COPY ./target/*.jar springboot-deploy.jar
# Exposer le port utilisé par Spring Boot
EXPOSE 8080
# Exécuter l'application Spring Boot
ENTRYPOINT ["java", "-jar", "springboot-deploy.jar"]